"""
Alert manager: create, persist, and route operational alerts.

Severity levels: debug < info < warning < error < critical

Alerts are stored in-memory (and optionally to DB) and can be consumed
by notification handlers (Slack, email, PagerDuty, etc.).
"""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Callable, Coroutine

import structlog

logger = structlog.get_logger(__name__)

# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

SEVERITY_LEVELS = ("debug", "info", "warning", "error", "critical")
SEVERITY_ORDER = {s: i for i, s in enumerate(SEVERITY_LEVELS)}


@dataclass
class Alert:
    """An operational alert generated by the trading system."""

    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    alert_type: str = ""
    message: str = ""
    severity: str = "info"              # debug | info | warning | error | critical
    ticker: str | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(tz=timezone.utc))
    acknowledged: bool = False
    extra: dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if self.severity not in SEVERITY_LEVELS:
            raise ValueError(
                f"Invalid severity '{self.severity}'. Must be one of {SEVERITY_LEVELS}."
            )

    @property
    def is_critical(self) -> bool:
        return self.severity == "critical"

    @property
    def severity_order(self) -> int:
        return SEVERITY_ORDER.get(self.severity, 1)

    def __str__(self) -> str:
        ticker_part = f"[{self.ticker}] " if self.ticker else ""
        return f"[{self.severity.upper()}] {ticker_part}{self.alert_type}: {self.message}"


# ---------------------------------------------------------------------------
# Alert manager
# ---------------------------------------------------------------------------


class AlertManager:
    """Create, store, and dispatch operational alerts.

    Features:
    - In-memory store with configurable max size (oldest purged first).
    - Per-severity and per-ticker filtering.
    - Pluggable notification handlers (async callbacks).
    - Optional DB persistence via injected save_fn.

    Usage::

        manager = AlertManager(min_log_severity="warning")
        manager.add_handler(send_to_slack)
        await manager.create_alert("risk_limit", "Daily loss exceeded", severity="critical")
    """

    def __init__(
        self,
        min_log_severity: str = "info",
        max_stored: int = 1000,
        db_save_fn: Callable[["Alert"], Coroutine[Any, Any, None]] | None = None,
    ) -> None:
        self.min_log_severity = min_log_severity
        self.max_stored = max_stored
        self._db_save_fn = db_save_fn

        self._alerts: list[Alert] = []
        self._handlers: list[Callable[["Alert"], Coroutine[Any, Any, None]]] = []

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def create_alert(
        self,
        alert_type: str,
        message: str,
        ticker: str | None = None,
        severity: str = "info",
        **extra: Any,
    ) -> Alert:
        """Create and dispatch an alert.

        Args:
            alert_type: Machine-readable category (e.g. "stop_loss_hit").
            message:    Human-readable description.
            ticker:     Optional associated ticker symbol.
            severity:   One of debug | info | warning | error | critical.
            **extra:    Additional metadata stored in alert.extra.

        Returns:
            The created Alert.
        """
        alert = Alert(
            alert_type=alert_type,
            message=message,
            ticker=ticker,
            severity=severity,
            extra=dict(extra),
        )

        # Log it
        if SEVERITY_ORDER.get(severity, 1) >= SEVERITY_ORDER.get(self.min_log_severity, 1):
            log_fn = getattr(logger, severity if severity != "critical" else "critical", logger.info)
            log_fn(
                "alert_created",
                alert_type=alert_type,
                ticker=ticker,
                message=message,
            )

        # Store in memory
        self._alerts.append(alert)
        if len(self._alerts) > self.max_stored:
            self._alerts = self._alerts[-self.max_stored :]

        # Persist to DB
        if self._db_save_fn:
            try:
                await self._db_save_fn(alert)
            except Exception as exc:
                logger.error("alert_db_save_failed", error=str(exc))

        # Dispatch to handlers
        for handler in self._handlers:
            try:
                await handler(alert)
            except Exception as exc:
                logger.error(
                    "alert_handler_failed",
                    handler=handler.__name__,
                    error=str(exc),
                )

        return alert

    def add_handler(
        self,
        handler: Callable[["Alert"], Coroutine[Any, Any, None]],
    ) -> None:
        """Register an async notification handler (e.g. Slack, email)."""
        self._handlers.append(handler)

    def remove_handler(
        self,
        handler: Callable[["Alert"], Coroutine[Any, Any, None]],
    ) -> None:
        """Remove a previously registered handler."""
        self._handlers = [h for h in self._handlers if h is not handler]

    # ------------------------------------------------------------------
    # Querying
    # ------------------------------------------------------------------

    def get_alerts(
        self,
        severity: str | None = None,
        ticker: str | None = None,
        alert_type: str | None = None,
        limit: int = 100,
        unacknowledged_only: bool = False,
    ) -> list[Alert]:
        """Query stored alerts with optional filters."""
        results = list(reversed(self._alerts))  # newest first

        if severity:
            min_order = SEVERITY_ORDER.get(severity, 0)
            results = [a for a in results if a.severity_order >= min_order]
        if ticker:
            results = [a for a in results if a.ticker == ticker]
        if alert_type:
            results = [a for a in results if a.alert_type == alert_type]
        if unacknowledged_only:
            results = [a for a in results if not a.acknowledged]

        return results[:limit]

    def acknowledge(self, alert_id: str) -> bool:
        """Mark an alert as acknowledged.  Returns True if found."""
        for alert in self._alerts:
            if alert.id == alert_id:
                alert.acknowledged = True
                return True
        return False

    def acknowledge_all(
        self,
        ticker: str | None = None,
        alert_type: str | None = None,
    ) -> int:
        """Acknowledge matching alerts.  Returns count."""
        count = 0
        for alert in self._alerts:
            if alert.acknowledged:
                continue
            if ticker and alert.ticker != ticker:
                continue
            if alert_type and alert.alert_type != alert_type:
                continue
            alert.acknowledged = True
            count += 1
        return count

    def count_unacknowledged(self, min_severity: str = "warning") -> int:
        min_order = SEVERITY_ORDER.get(min_severity, 0)
        return sum(
            1 for a in self._alerts
            if not a.acknowledged and a.severity_order >= min_order
        )

    def get_recent_critical(self, limit: int = 10) -> list[Alert]:
        return self.get_alerts(severity="critical", limit=limit)

    def clear(self) -> None:
        """Clear all stored alerts (useful for testing)."""
        self._alerts.clear()
